M48
; DRILL file {KiCad (6.0.10)} date Mon Nov 27 04:30:29 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-27T04:30:29+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X2.4291Y-5.1339
T2
X2.9685Y-5.3661
X2.9685Y-5.4646
X3.1654Y-5.1693
X3.3622Y-5.3661
X3.3622Y-5.4646
T3
X5.8177Y-1.1665
T0
M30
